product: hr

object_dependencies:
  - target: dds.dim_hr_department
    depends_on:
      - raw.hr_department_history_raw

  - target: dds.dim_position
    depends_on:
      - raw.hr_employee_master_raw
      - raw.hr_position_history_raw

  - target: dds.dim_hr_employee
    depends_on:
      - raw.hr_employee_master_raw
      - dds.dim_hr_department
      - dds.dim_position

  - target: dds.fct_employee_position_history
    depends_on:
      - raw.hr_position_history_raw
      - dds.dim_hr_employee
      - dds.dim_position
      - dds.dim_hr_department

  - target: dds.fct_employee_absence
    depends_on:
      - raw.hr_absence_events_raw
      - dds.dim_hr_employee

  - target: dds.fct_employee_activity_signal
    depends_on:
      - raw.hr_overtime_events_raw
      - raw.hr_dismissal_signals_raw
      - dds.dim_hr_employee

  - target: dds.fct_employee_hr_snapshot
    depends_on:
      - dds.dim_hr_employee
      - dds.fct_employee_absence
      - dds.fct_employee_activity_signal

  - target: dm.employee_hr_profile_report
    depends_on:
      - dds.fct_employee_hr_snapshot
      - dds.dim_hr_employee
      - dds.dim_position
      - dds.dim_hr_department

  - target: dm.v_employee_instability_signals
    depends_on:
      - dds.fct_employee_activity_signal
      - dds.dim_hr_employee
      - dds.dim_position
      - dds.dim_hr_department
      - dds.fct_employee_hr_snapshot